Emlak Fiyatlarını Yapay Zeka Kullanarak Tahmin Etme

Bunun için linear regresyon kullanacağız.

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [9]:
df = pd.read_csv('multilinearregression.csv',sep=';')
df.head()

alan  odasayisi  binayasi   fiyat
0   180          5        10  510000
1   225          4        18  508000
2   260          3         2  548000
3   320          6        10  650000
4   335          4         9  628000

Verisetimizin bağımlı ve bağımsız değişkenlerini seçtikten sonra bunları train ve test olarak ayırıyoruz.

In [25]:
x = df[['alan','odasayisi','binayasi']]
y = df['fiyat']

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

Linear regresyon modeli oluşturup fit ediyoruz:

In [28]:
reg = LinearRegression().fit(x_train, y_train)

Tahmin:

In [31]:
reg.predict([[275,3,11]])

C:\Users\dlara\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([564340.61635717])

In [33]:
reg.predict([[230,6,0]])

C:\Users\dlara\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578790.79415251])

In [35]:
reg.predict([[355,3,20]])

C:\Users\dlara\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([634560.41090478])

Modelimizin sabit sayısına ve katsayısına ulaşmak için:

In [37]:
reg.coef_

array([ 1056.72066377, 14834.33425524, -1590.87317266])

In [39]:
reg.intercept_

246739.0359541683

Birden fazla veriyle predict yapmak:

In [49]:
reg.predict([[230, 4, 10], [230, 6, 0], [355, 3, 20]])

C:\Users\dlara\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([533213.39391545, 578790.79415251, 634560.41090478])